config/routes.rb
Rails.application.routes.draw do

  get 'journey_habits/create'
  get 'responses/create'
  get 'moods/checkin'
  get 'moods/checkin2'
  get 'lessons/show'

  get 'activities/show'
  get 'videos/show'
  get 'lessons/show'
  get 'lessons/:id/videos/:id/rewards', to: 'videos#rewards'
  get 'habits/:id//rewards', to: 'habits#rewards'
  get 'journeys/show'
  get 'users/home'
  get 'users/show'
  get 'users/social'
  get 'users/tools'
  get 'users/support'
  get 'users/teacherhome'
  root to: 'pages#home'
  get 'checkin', to: 'pages#checkin'
  get 'checkin2', to: 'pages#checkin2'

  devise_for :users
  get 'users', to: "users#home"
  get 'users/social', to: 'users#social'
  get 'users/tools', to: 'users#tools'
  get 'users/support', to: 'users#support'

  resources :journeys, only: [:show]
  resources :tools, only: [:show]
  resources :habits, only: [:show, :create]
  resources :lessons, only: [:show] do
    resources :activities, only: [:show]
    resources :videos, only: [:show]
  end

  resources :questions, only: [] do
    resources :responses, only: [:create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :lesson
  has_many :questions
  has_many :responses, through: :questions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
    has_many :badge_users
end

app/models/badge_user.rb
class BadgeUser < ApplicationRecord
  belongs_to :user
  belongs_to :badge
  validates :user, uniqueness: { scope: :badge }
end

app/models/daily_mood.rb
class DailyMood < ApplicationRecord
  belongs_to :user
  belongs_to :mood
end

app/models/habit.rb
class Habit < ApplicationRecord
    has_many :questions, dependent: :destroy
    has_many :journey_habits
    has_many :journeys, through: :journey_habits
    has_many :responses, through: :questions

    accepts_nested_attributes_for :responses

end

app/models/journey.rb
class Journey < ApplicationRecord
  belongs_to :user
  has_many :journey_lessons
  has_many :journey_habits
  has_many :lessons, through: :journey_lessons
  validates :name, presence: true
end

app/models/journey_habit.rb
class JourneyHabit < ApplicationRecord
  belongs_to :journey
  belongs_to :habit
  has_many :questions, through: :habits
  # validates_uniqueness_of :habit, conditions: -> { where("DATE(created_at) = ?", Date.today) }
  def self.totals_by_user(current_user)
    @students = User.where(teacher: false, school_class:current_user.school_class)
    @journeyhabits = JourneyHabit.where(@students.include? :user)
    @students.map do |student| 
      [
        student.first_name,
        student.journeys.last.journey_habits.count
      ]
    end
  end
end

app/models/journey_lesson.rb
class JourneyLesson < ApplicationRecord
  belongs_to :lesson
  belongs_to :journey
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :journey_lessons
  has_many :activities, dependent: :destroy
  has_many :videos, dependent: :destroy
  validates :name, :description, presence: true
end

app/models/mood.rb
class Mood < ApplicationRecord
    validates :name, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :activity, optional: true
  belongs_to :habit, optional: true
  has_many :responses
  validates :question, presence: true
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :question
  validates :content, presence: true
  belongs_to :user
  
  
end

app/models/tool.rb
class Tool < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :journeys, dependent: :destroy
  validates :first_name, :last_name, presence: true
  has_one_attached :photo
  has_many :journey_habits, through: :journeys
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :lesson
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController
  def checkin
  end

  def checkin2
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :no_banner

  def home
    @home = true
    if current_user
      @journeys = current_user.journeys
      @current_journey = @journeys.last
      redirect_to users_home_path
    # else
    #   redirect_to new_user_session_path
    end
  end

  def checkin
    @moods = Mood.all
  end

  def checkin2
    @daily_mood = DailyMood.new(user: current_user, mood:Mood.find(params["mood"].to_i))
    @daily_mood.save
    redirect_to users_home_path
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :cream_banner

  def show
    @tool = Tool.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :green_banner, only: :social
  before_action :cream_banner, only: :tools

  def home
    @short_leaderboard = User.where(teacher:false).order('xp DESC').limit(4)
    if current_user.teacher
      redirect_to '/users/teacherhome'
    end
      @journeys = current_user.journeys
      if @journeys.count > 0
        @journey = @journeys.last
        @journey_lessons = @journey.journey_lessons
        @completed_lessons = @journey_lessons.where(complete: true)
        @journey_progress = ((@completed_lessons.length.to_f / @journey_lessons.length)*100).to_i
      end
      @user_badges = BadgeUser.where(user: current_user)
      @journey_habits = JourneyHabit.where(journey: @journeys.last).order('created_at DESC')
      @daily_mood = DailyMood.find_by(created_at: Date.today.beginning_of_day..Date.today.end_of_day, user: current_user)
      unless @daily_mood  || current_user.teacher
        redirect_to '/checkin'
      end


    # streak logic
    unless current_user.teacher
      counter = 0
      last_habit = nil
      if @journey_habits.length > 0 && @journey_habits.first.created_at.strftime("%j").to_i == Date.today.strftime("%j").to_i
        @journey_habits.each do |journey_habit|
            if last_habit == nil
              last_habit = journey_habit
            elsif
              (last_habit.created_at.strftime("%j").to_i - journey_habit.created_at.strftime("%j").to_i) == 1
              counter += 1
              last_habit = journey_habit
            else
              break
            end
          end
          counter += 1
      end
      @streak = counter
    end

  end

  def show
  end

  def social
    @leaderboard = User.where(teacher:false).order('xp DESC').limit(10)
    @journeys = current_user.journeys
    @students = User.where(teacher: false, school_class:current_user.school_class)
    @badge_activity = BadgeUser.where(@students.include? :user)
    @habit_activity = JourneyHabit.where(@students.include? :user)
    @recent_activity = (@badge_activity+@habit_activity).sort_by { |activity| activity.created_at }.reverse.first(10)

  end

  def tools
    @tools = Tool.all
    @journeys = current_user.journeys
  end

  def support
    @journeys = current_user.journeys
  end

  def teacherhome
    @students = User.where(teacher: false, school_class:current_user.school_class)
    @badge_activity = BadgeUser.where(@students.include? :user)
    @mood_activity = DailyMood.where(@students.include? :user)
    @habit_activity = JourneyHabit.where(@students.include? :user)
    @recent_activity = (@badge_activity+@mood_activity+@habit_activity).sort_by { |activity| activity.created_at }.reverse.first(10)
    @habit_data = JourneyHabit.totals_by_user(current_user)
    @negative_moods = %w(🙁 😡 😰 😯 🤕)
  end
private

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/tools/show.html.erb
<div class="absolute-header grey">
  <h1><%=@tool.name%></h1>
</div>

  <div>
    <h5 class="mt-4">Meditation Benefits</h5>
    <p>
      Less stress translates to less anxiety.
      For example, an eight-week study of mindfulness meditation helped participants reduce their anxiety.
      It also reduced symptoms of anxiety disorders, such as phobias, social anxiety, paranoid thoughts, obsessive-compulsive behaviors and panic attacks (9).
    </p>
    <div class="audio-container">
      <p><strong>Meditation Sounds</strong></p>
      <%= audio_tag "meditationsounds", controls: true%>
      <%= image_tag "meditation", alt: "alttext" %>
    </div>
  </div>

app/views/users/home.html.erb
<div class="absolute-header">
  <h1>Home</h1>
  <p>Challenge overview</p>
</div>

<div class="week-header text-center mb-3 mr-3">
  <h2>Week 1 of 6</h2>
</div>
<h3><strong>Challenge Statistics</strong></h3>

<%# journey %>
<% if @journeys.length > 0 %>
    <div class="dashboard-element dashboard-progress d-flex align-items-center">
        <div><p class="mb-0">Progress: <%= @journey_progress %>%</p></div>
        <div class="progress dashboard-progressbar ml-2">
            <div class="progress-bar" role="progressbar" style="width: <%= @journey_progress %>%" aria-valuenow="<%= @journey_progress %>" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
    </div>
<% end %>
<div class="d-flex flex-wrap justify-content-center mb-4">
    <%# xp %>
    <div class="d-flex xp-streak">
        <div class="dashboard-element streak mr-2">
            <h4 class="m-0"><%= image_tag "007-star.svg", :height=>"30px" %> <strong><%= @user_badges.length %></strong> badges</h4>
        </div>
        <div class="dashboard-element xp ml-2">
            <h4 class="m-0"><%= image_tag "095-diamond.svg", :height=>"30px" %>
                <% if current_user.xp %>
                    <strong><%= current_user.xp %></strong>
                <% else %>
                    <strong>0</strong>
                <% end %>
                points
            </h4>
        </div>
    </div>
    <div class="dashboard-element dashboard-progress streak d-flex align-items-center">
        <h4 class="m-0 mr-2"><strong><%= @streak %></strong> day streak</h4>
        <% @streak.times do%>
            <%= image_tag "009-fire.svg", :height=>"30px" %>
        <% end %>
    </div>
    <div class="d-flex">
      <% if @journeys.length > 0 %>
        <div class="mr-3">
          <%= link_to "Next Activity", journey_path(@journeys.last), class: "btn btn-main" %>
        </div>
      <% end %>
      <% sleep_habit = Habit.last %>
      <% if current_user.journey_habits.empty? %>
        <div class="ml-3">
          <%= link_to "Log Sleep", habit_path(sleep_habit), class: "btn btn-main" %>
        </div>
      <% elsif current_user.journey_habits.last.created_at.to_date != Date.current %>
        <div class="ml-3">
          <%= link_to "Log Sleep", habit_path(sleep_habit), class: "btn btn-main" %>
        </div>
      <% else %>
        <div class="btn btn-main ml-3" style="opacity: .5;" >Log Sleep </div>
      <% end %>
    </div>
</div>
    <h3 id="leaderboard-header"><strong>Challenge Leaderboard</strong></h3>
<div class="dashboard-leaderboard dashboard-element mb-4">
        <table style="width: 100%" class="table leaderboard mb-0">
            <% counter = 1 %>
            <% @short_leaderboard.each do |user| %>
                <tr class=<%="leaderboard-current-user" if user == current_user %>>
                    <td class="leaderboard-position"><%= counter %></td>
                    <td class="leaderboard-avatar"><%= cl_image_tag user.photo.key, :gravity=>"faces", :crop=>"fill", class: "avatar m-1", alt: "avatar-large" %></td>
                    <td><%= user.first_name %></td>
                    <td class="leaderboard-xp"><%= user.xp %> XP</td>
                    <% counter += 1 %>
                </tr>
            <% end %>
        </table>
</div>
<%# badges %>

            <h3>Badges</h3>

<div class="dashboard-element">
    <% if  @user_badges %>
        <% if  @user_badges.length > 0 %>
            <div class="user-badges d-flex flex-wrap justify-content-start">
                <% @user_badges.each do |user_badge| %>
                    <div class="badge-card d-flex align-items-center">
                        <div class="d-flex align-items-center flex-column user-badge">
                            <%= image_tag "badges/#{user_badge.badge.name.gsub(/\s+/, "")}.png", alt: user_badge.badge.name %>
                            <p class="mb-auto"><%= user_badge.badge.name %></p>
                        </div>
                        <div class="badge-card-text ml-2">
                            <p><strong><%= user_badge.badge.name.capitalize %></strong></p>
                            <p class="grey sml-text">You earned this badge on <%= user_badge.created_at.strftime("%A %d %B") %></p>
                        </div>
                    </div>
                <% end %>
            </div>
        <% else %>
            <h3>You currently have no badges</h3>
        <% end %>
    <% end %>
</div>
<div style="height:50px;"></div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/social.html.erb
<div class="absolute-header">
  <h1>Social Dashboard</h1>
  <p>See your friends progress</p>
</div>

<h3 class="mt-4"><strong>Challenge Leaderboard</strong></h3>
<div class="dashboard-element mb-4">
  <table style="width: 100%" class="table leaderboard mb-0">
          <% counter = 1 %>

          <% @leaderboard.each do |user| %>
              <tr class=<%="leaderboard-current-user" if user == current_user %>>
                  <td class="leaderboard-position"><%= counter %></td>
                  <td class="leaderboard-avatar"><%= cl_image_tag user.photo.key, :gravity=>"faces", :crop=>"fill", class: "avatar", alt: "avatar-large" %></td>
                  <td><%= user.first_name %></td>
                  <td class="leaderboard-xp"><%= user.xp %> XP</td>
                  <% counter += 1 %>
              </tr>
          <% end %>
  </table>
</div>


  <h3><strong>The Feed</strong></h3>
  <% @recent_activity.each do |activity| %>
      <% if activity.is_a?(BadgeUser) %>

        <div class="feed-container mb-4">
          <div class="feed-content d-flex justify-content-between">
            <div class="d-flex justify-content-start">
              <div class="feed-avatar align-self-start">
                <%= cl_image_tag activity.user.photo.key, :gravity=>"faces", :crop=>"fill", class: "avatar-large m-2", alt: "avatar-large" %>
              </div>
              <div class="feed-info align-self-center">
                <div class="feed-name d-flex justify-content-start flex-grow-1">
                  <div>
                    <p><%= activity.user.first_name %> has earned the <%= activity.badge.name %> badge.</p>
                    <p class="feed-date sml-text"><%= activity.created_at.strftime("%A %d %B") %></p>
                  </div>
                </div>
              </div>
            </div>
            <div class="feed-icon">
              <div class="d-flex align-items-center flex-column user-badge">
                        <%= image_tag "badges/#{activity.badge.name.gsub(/\s+/, "")}.png", alt: activity.badge.name %>
                        <p class="mb-auto"><%= activity.badge.name %></p>
              </div>
            </div>
          </div>
          <div class="feed-kudos d-flex flex-wrap justify-content-center py-1">
            <p>Give Kudos 🙌</p>
          </div>
        </div>
      <% else %>
        <div class="feed-container my-4">
          <div class="feed-content d-flex justify-content-between">
            <div class="d-flex justify-content-start">
              <div class="feed-avatar align-self-start">
                <%= cl_image_tag activity.journey.user.photo.key, :gravity=>"faces", :crop=>"fill", class: "avatar-large m-2", alt: "avatar-large" %>
              </div>
              <div class="feed-info align-self-center">
                <div class="feed-name d-flex justify-content-start flex-grow-1">
                  <div>
                    <p><%= activity.journey.user.first_name %> has logged the <%= activity.habit.name %> habit.</p>
                    <p class="feed-date sml-text"><%= activity.created_at.strftime("%A %d %B") %></p>
                  </div>
                </div>
              </div>
            </div>
            <div class="feed-icon">
              <div class="d-flex align-items-center flex-column user-badge">
                        <%= image_tag "sleep.png", alt: "sleep", class: "mb-2" %>
                        <p class="mb-auto"><%= activity.habit.name %></p>
              </div>
            </div>
          </div>
          <div class="feed-kudos d-flex flex-wrap justify-content-center py-1">
            <p>Give Kudos 🙌</p>
          </div>
        </div>
      <% end %>
  <% end %>
<div style="height:50px;"></div>

app/views/users/support.html.erb
<div class="absolute-header">
  <h1>Support </h2>
  <p>When you need support now</p>
</div>

<div class="container-support">
<div class="mt-5 mb-5">
  <p>Sometimes you just need to speak to someone.
  That’s OK, we all have times where we just dont feel right!
  When you feel this way its best to speak to someone you trust.
  You can reach out to your teacher, someone close to you or services that have friendly
  people waiting for you. <br><br>
  What would you prefer?</p>
</div>


<div class="d-flex flex-column justify-content-center">
 <a class="btn btn-main orange w-75" href="#">Speak to Service</a>
 <a class="btn btn-main w-75" href="#">Speak to Counsellor</a>
</div>
<div style="height:50px;"></div>
</div>

app/views/users/teacherhome.html.erb
<h2 class="absolute-header"><%= current_user.first_name.capitalize %> <%= current_user.last_name.capitalize %><p>Teacher Dashboard</p></h2>


<div class="dashboard-element teacher-info">
  <h2><%= current_user.school_name %></h2>
  <h4><%= current_user.school_class %> - <strong><%= @students.count %></strong> students
</div>

<div class="dashboard-element">
  <h5>Student Activity</h5>
  <% @recent_activity.each do |activity| %>
      
      <p><% if activity.class == BadgeUser %>
              <div class="activity badge-activity d-flex mb-1">
                <div>
                  <%= cl_image_tag activity.user.photo.key, :gravity=>"faces", :crop=>"fill", class: "avatar m-1", alt: "avatar-large" %>
                </div>
                <div>
                  <%= activity.user.first_name %> earned the <%= activity.badge.name %> badge.
                  <div class="grey"><%= activity.created_at.strftime("%A %d %B")%></div>
                </div>
              </div>
      <% elsif activity.class == JourneyHabit %>
              <div class="activity habit-activity d-flex mb-1">
                <div>
                  <%= cl_image_tag activity.journey.user.photo.key, :gravity=>"faces", :crop=>"fill", class: "avatar m-1", alt: "avatar-large" %>
                </div>
                <div>
                  <%= activity.journey.user.first_name %> logged the <%= activity.habit.name %> habit.
                  <div class="grey"><%= activity.created_at.strftime("%A %d %B")%></div>
                </div>
              </div>
      <% elsif activity.class == DailyMood %>
              <div class="activity mood-activity d-flex mb-1 <%="attention" if @negative_moods.include? activity.mood.name %>">
                <div>
                  <%= cl_image_tag activity.user.photo.key, :gravity=>"faces", :crop=>"fill", class: "avatar m-1", alt: "avatar-large" %>
                </div>
                <div>
                  <%= activity.user.first_name %> logged the <%= activity.mood.name %> mood.
                  <div class="grey"><%= activity.created_at.strftime("%A %d %B")%></div>
                </div>
              </div>
      <% end %></p>
  <% end %>
</div>

<div id="chart" style="width: webkit-fill-available; height: 400px;"></div>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<%= javascript_tag do -%>
  google.charts.load('current', {'packages':['bar']});
  google.charts.setOnLoadCallback(drawChart);

  function drawChart() {
    var data = JSON.parse('<%= @habit_data.to_json.html_safe -%>');
    data = [['Student', 'Habits Logged']].concat(data);
    data = google.visualization.arrayToDataTable(data);
    var options = {
      title: 'Habits logged by students'
    };

    var chart = new google.charts.Bar(document.getElementById('chart'));
    chart.draw(data, google.charts.Bar.convertOptions(options));
  }
<% end -%>
<div style="height:50px;"></div>

app/views/users/tools.html.erb
<div class="absolute-header grey">
  <h1>Tools</h1>
  <p>Your toolkit for a happy mind</p>
</div>

<div class="cards-tool mt-4">
<% @tools.each do |tool| %>
  <div class="card-trip-index mb-2">
                  <%=  image_tag("tools/#{tool.photo}", class: "tool-card") %>
      <div class="card-trip-infos">
        <p><%= link_to "#{tool.name}", tool_path(tool), class: "no-decoration"%></p>
      </div>
    </div>
    <% end %>
  </div>
</div>
<div style="height:50px;"></div>