config/routes.rb
Rails.application.routes.draw do

  get 'journey_habits/create'
  get 'responses/create'
  get 'moods/checkin'
  get 'moods/checkin2'
  get 'lessons/show'

  get 'activities/show'
  get 'videos/show'
  get 'lessons/show'
  get 'lessons/:id/videos/:id/rewards', to: 'videos#rewards'
  get 'habits/:id//rewards', to: 'habits#rewards'
  get 'journeys/show'
  get 'users/home'
  get 'users/show'
  get 'users/social'
  get 'users/tools'
  get 'users/support'
  get 'users/teacherhome'
  root to: 'pages#home'
  get 'checkin', to: 'pages#checkin'
  get 'checkin2', to: 'pages#checkin2'

  devise_for :users
  get 'users', to: "users#home"
  get 'users/social', to: 'users#social'
  get 'users/tools', to: 'users#tools'
  get 'users/support', to: 'users#support'

  resources :journeys, only: [:show]
  resources :tools, only: [:show]
  resources :habits, only: [:show, :create]
  resources :lessons, only: [:show] do
    resources :activities, only: [:show]
    resources :videos, only: [:show]
  end

  resources :questions, only: [] do
    resources :responses, only: [:create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :lesson
  has_many :questions
  has_many :responses, through: :questions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
    has_many :badge_users
end

app/models/badge_user.rb
class BadgeUser < ApplicationRecord
  belongs_to :user
  belongs_to :badge
  validates :user, uniqueness: { scope: :badge }
end

app/models/daily_mood.rb
class DailyMood < ApplicationRecord
  belongs_to :user
  belongs_to :mood
end

app/models/habit.rb
class Habit < ApplicationRecord
    has_many :questions, dependent: :destroy
    has_many :journey_habits
    has_many :journeys, through: :journey_habits
    has_many :responses, through: :questions

    accepts_nested_attributes_for :responses

end

app/models/journey.rb
class Journey < ApplicationRecord
  belongs_to :user
  has_many :journey_lessons
  has_many :journey_habits
  has_many :lessons, through: :journey_lessons
  validates :name, presence: true
end

app/models/journey_habit.rb
class JourneyHabit < ApplicationRecord
  belongs_to :journey
  belongs_to :habit
  has_many :questions, through: :habits
  # validates_uniqueness_of :habit, conditions: -> { where("DATE(created_at) = ?", Date.today) }
  def self.totals_by_user(current_user)
    @students = User.where(teacher: false, school_class:current_user.school_class)
    @journeyhabits = JourneyHabit.where(@students.include? :user)
    @students.map do |student| 
      [
        student.first_name,
        student.journeys.last.journey_habits.count
      ]
    end
  end
end

app/models/journey_lesson.rb
class JourneyLesson < ApplicationRecord
  belongs_to :lesson
  belongs_to :journey
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :journey_lessons
  has_many :activities, dependent: :destroy
  has_many :videos, dependent: :destroy
  validates :name, :description, presence: true
end

app/models/mood.rb
class Mood < ApplicationRecord
    validates :name, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :activity, optional: true
  belongs_to :habit, optional: true
  has_many :responses
  validates :question, presence: true
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :question
  validates :content, presence: true
  belongs_to :user
  
  
end

app/models/tool.rb
class Tool < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :journeys, dependent: :destroy
  validates :first_name, :last_name, presence: true
  has_one_attached :photo
  has_many :journey_habits, through: :journeys
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :lesson
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController
  def checkin
  end

  def checkin2
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :no_banner

  def home
    @home = true
    if current_user
      @journeys = current_user.journeys
      @current_journey = @journeys.last
      redirect_to users_home_path
    # else
    #   redirect_to new_user_session_path
    end
  end

  def checkin
    @moods = Mood.all
  end

  def checkin2
    @daily_mood = DailyMood.new(user: current_user, mood:Mood.find(params["mood"].to_i))
    @daily_mood.save
    redirect_to users_home_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yooka</title>
    <meta name="description" content="<%= meta_description %>">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable"  content="yes">
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>"/>
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />
     <%= render 'shared/ios_pwa_links' %>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>


  <body class="<%= "background-brand-color" if devise_controller? %>">
      <%= render "shared/banner" %>
      <%= render "shared/top-navbar" unless @home || @user%>
  <div class="d-flex justify-content-center">
    <div class="phone-container">
      <% if controller_name == 'videos' && action_name == 'show'%>
        <%= yield %>
      <% elsif @home  %>
        <div class="home-container">
          <%= yield %>
        </div>
      <%  else %>
        <div class="container">
          <%= yield %>
        </div>
      <%  end %>
    </div>
    </div>
      <%= render "shared/navbar" unless @home %>
  </body>
</html>

app/views/shared/_banner.html.erb
  <% if @show_banner=='blue'%>
   <%= image_tag "bluelesson.png", alt: "alttext", class: "banner-width" %>
  <% elsif @show_banner=='orange' %>
    <%= image_tag "orangbanner.png", alt: "alttext", class: "banner-width" %>
  <% elsif @show_banner == 'curved-blue' %>
    <%= image_tag "bluecurved.png", alt: "alttext", class: "banner-width" %>
  <% elsif @show_banner == 'green' %>
    <%= image_tag "green.png", alt: "alttext", class: "banner-width" %>
  <% elsif @show_banner == 'cream' %>
    <%= image_tag "cream.png", alt: "alttext", class: "banner-width" %>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<% unless params[:controller]=="devise/sessions" ||
    params[:controller]=="devise/registrations" ||
    params[:controller]=="activities" ||
    params[:controller]=="videos" ||
    params[:controller]=="pages" ||
    params[:controller]=="habits" %>

  <nav class="nav">
    <% if current_user %>
      <%= link_to users_home_path, class: "nav__link" do %>
        <i class="material-icons nav__icon">home</i>
        <span class="nav__text">Home</span>
      <% end %>
      <%= link_to journeys_show_path, class: "nav__link " do %>
        <i class="material-icons nav__icon">school</i>
        <span class="nav__text">Learn</span>
      <% end %>
      <%= link_to users_social_path, class: "nav__link" do %>
        <i class="material-icons nav__icon">people</i>
        <span class="nav__text">Social</span>
      <% end %>
      <%= link_to users_tools_path, class: "nav__link" do %>
        <i class="material-icons nav__icon">build</i>
        <span class="nav__text">Tools</span>
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete, class: "nav__link nav__link--active" do %>
        <i class="material-icons nav__icon">clear</i>
        <span class="nav__text">Sign Out</span>
      <% end %>
    <% end %>
  </nav>

<% end %>

app/views/shared/_popup.html.erb
<div class="popup-wrap">
    <div class="popup-box">
      <h2>Title of Popup</h2>
      <h3>A sub-heading for the popup with a little description.</h3>
      <a class="close-btn popup-close" href="#">x</a>
    </div>
</div>

app/views/shared/_top-navbar.html.erb
<div class="top-navbar-container fixed-top">
  <% unless params[:controller]=="journeys" && params[:action]=="show" ||
    params[:controller]=="users" || params[:controller]=="devise/sessions" ||
    params[:controller]=="devise/registrations" ||
    params[:controller]=="activities"%>
    <%= link_to :back, class: "back-item" do %>
      <i class="material-icons md-36">keyboard_backspace</i>
    <% end %>
  <% else %>
    <% if params[:controller]=="activities" %>
    <%= link_to lesson_path(@lesson), class: "back-item" do %>
    <i class="material-icons md-36">keyboard_backspace</i>
    <% end %>
  <% end %>
  <% end %>
  <div></div>
  <% unless params[:controller]=="activities" ||
    params[:controller]=="habits" %>
  <%= link_to "/users/support", class: "support-item" do %>
    <i class="material-icons md-36">support</i>
  <% end %>
  <%end%>
</div>