config/routes.rb
Rails.application.routes.draw do

  get 'journey_habits/create'
  get 'responses/create'
  get 'moods/checkin'
  get 'moods/checkin2'
  get 'lessons/show'

  get 'activities/show'
  get 'videos/show'
  get 'lessons/show'
  get 'lessons/:id/videos/:id/rewards', to: 'videos#rewards'
  get 'habits/:id//rewards', to: 'habits#rewards'
  get 'journeys/show'
  get 'users/home'
  get 'users/show'
  get 'users/social'
  get 'users/tools'
  get 'users/support'
  get 'users/teacherhome'
  root to: 'pages#home'
  get 'checkin', to: 'pages#checkin'
  get 'checkin2', to: 'pages#checkin2'

  devise_for :users
  get 'users', to: "users#home"
  get 'users/social', to: 'users#social'
  get 'users/tools', to: 'users#tools'
  get 'users/support', to: 'users#support'

  resources :journeys, only: [:show]
  resources :tools, only: [:show]
  resources :habits, only: [:show, :create]
  resources :lessons, only: [:show] do
    resources :activities, only: [:show]
    resources :videos, only: [:show]
  end

  resources :questions, only: [] do
    resources :responses, only: [:create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :lesson
  has_many :questions
  has_many :responses, through: :questions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
    has_many :badge_users
end

app/models/badge_user.rb
class BadgeUser < ApplicationRecord
  belongs_to :user
  belongs_to :badge
  validates :user, uniqueness: { scope: :badge }
end

app/models/daily_mood.rb
class DailyMood < ApplicationRecord
  belongs_to :user
  belongs_to :mood
end

app/models/habit.rb
class Habit < ApplicationRecord
    has_many :questions, dependent: :destroy
    has_many :journey_habits
    has_many :journeys, through: :journey_habits
    has_many :responses, through: :questions

    accepts_nested_attributes_for :responses

end

app/models/journey.rb
class Journey < ApplicationRecord
  belongs_to :user
  has_many :journey_lessons
  has_many :journey_habits
  has_many :lessons, through: :journey_lessons
  validates :name, presence: true
end

app/models/journey_habit.rb
class JourneyHabit < ApplicationRecord
  belongs_to :journey
  belongs_to :habit
  has_many :questions, through: :habits
  # validates_uniqueness_of :habit, conditions: -> { where("DATE(created_at) = ?", Date.today) }
  def self.totals_by_user(current_user)
    @students = User.where(teacher: false, school_class:current_user.school_class)
    @journeyhabits = JourneyHabit.where(@students.include? :user)
    @students.map do |student| 
      [
        student.first_name,
        student.journeys.last.journey_habits.count
      ]
    end
  end
end

app/models/journey_lesson.rb
class JourneyLesson < ApplicationRecord
  belongs_to :lesson
  belongs_to :journey
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :journey_lessons
  has_many :activities, dependent: :destroy
  has_many :videos, dependent: :destroy
  validates :name, :description, presence: true
end

app/models/mood.rb
class Mood < ApplicationRecord
    validates :name, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :activity, optional: true
  belongs_to :habit, optional: true
  has_many :responses
  validates :question, presence: true
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :question
  validates :content, presence: true
  belongs_to :user
  
  
end

app/models/tool.rb
class Tool < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :journeys, dependent: :destroy
  validates :first_name, :last_name, presence: true
  has_one_attached :photo
  has_many :journey_habits, through: :journeys
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :lesson
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :blue_banner

  def show
    @lesson = Lesson.find(params[:id])
  end
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController
  def checkin
  end

  def checkin2
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :no_banner

  def home
    @home = true
    if current_user
      @journeys = current_user.journeys
      @current_journey = @journeys.last
      redirect_to users_home_path
    # else
    #   redirect_to new_user_session_path
    end
  end

  def checkin
    @moods = Mood.all
  end

  def checkin2
    @daily_mood = DailyMood.new(user: current_user, mood:Mood.find(params["mood"].to_i))
    @daily_mood.save
    redirect_to users_home_path
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :cream_banner

  def show
    @tool = Tool.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/lessons/show.html.erb
<div class="absolute-header">
  <h1><%= @lesson.topic.capitalize %></h1>
</div>

<div class="lesson-main-description mt-4">
  <p class="lesson-name"><%= @lesson.name.capitalize %></p>
  <p class="lesson-description"><%= @lesson.description %></p>
  <p class="lesson-time">- Time to complete lesson - <%= @lesson.time_to_complete %> mins</p>
</div>

<div class="author-background">
  <div class="d-flex">
    <%= image_tag @lesson.author_photo, class: "avatar-large m-3", id: "author-img" %>
    <div>
      <div class="author">
        <h5 class="author-name"><%= @lesson.author.split.map(&:capitalize).join(' ') %></h5>
        <p class="author-description"><%= @lesson.author_description.truncate(44) %></p>
      </div>
    </div>
  </div>
</div>

<% @lesson.videos.each do |video| %>
  <% if video.lesson.journey_lessons.find { |jl| jl.journey.user_id == current_user.id }.video_watched == true %>
    <div class="lesson-card-complete mb-3">
      <%= image_tag video.photo %>
      <div class="lesson-card-infos">
        <h2> Video: <%= video.name %> </h2>
        <p>Video • <%= video.time_to_complete %> mins</p>
      </div>
    </div>
  <% else %>
    <%= link_to lesson_video_path(@lesson, video) do  %>
      <div class="lesson-card mb-3">
        <%= image_tag video.photo %>
        <div class="lesson-card-infos">
          <h2> Video: <%= video.name %> </h2>
          <p>Video • <%= video.time_to_complete %> mins</p>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

   <% @lesson.activities.each do |activity| %>
    <% user_responses = activity.responses.where(user: current_user) %>
    <% unanswered_questions = activity.questions - user_responses.map { |r| r.question} %>
    <% if unanswered_questions.count == 0 %>
        <div class="lesson-card-complete mb-2">
          <%= image_tag activity.photo %>
          <div class="lesson-card-infos">
            <h2> <%= activity.name %> </h2>
            <p>Activity • <%= activity.time_to_complete %> mins</p>
          </div>
        </div>
      <% else %>
        <%= link_to lesson_activity_path(@lesson, activity) do  %>
            <div class="lesson-card mb-2">
              <%= image_tag activity.photo %>
              <div class="lesson-card-infos">
                <h2> <%= activity.name %> </h2>
                <p>Activity • <%= activity.time_to_complete %> mins</p>
              </div>
            </div>
            <% end %>
      <% end %>
    <% end %>
    <div style="height:50px;"></div>