config/routes.rb
Rails.application.routes.draw do

  get 'journey_habits/create'
  get 'responses/create'
  get 'moods/checkin'
  get 'moods/checkin2'
  get 'lessons/show'

  get 'activities/show'
  get 'videos/show'
  get 'lessons/show'
  get 'lessons/:id/videos/:id/rewards', to: 'videos#rewards'
  get 'habits/:id//rewards', to: 'habits#rewards'
  get 'journeys/show'
  get 'users/home'
  get 'users/show'
  get 'users/social'
  get 'users/tools'
  get 'users/support'
  get 'users/teacherhome'
  root to: 'pages#home'
  get 'checkin', to: 'pages#checkin'
  get 'checkin2', to: 'pages#checkin2'

  devise_for :users
  get 'users', to: "users#home"
  get 'users/social', to: 'users#social'
  get 'users/tools', to: 'users#tools'
  get 'users/support', to: 'users#support'

  resources :journeys, only: [:show]
  resources :tools, only: [:show]
  resources :habits, only: [:show, :create]
  resources :lessons, only: [:show] do
    resources :activities, only: [:show]
    resources :videos, only: [:show]
  end

  resources :questions, only: [] do
    resources :responses, only: [:create]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :lesson
  has_many :questions
  has_many :responses, through: :questions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
    has_many :badge_users
end

app/models/badge_user.rb
class BadgeUser < ApplicationRecord
  belongs_to :user
  belongs_to :badge
  validates :user, uniqueness: { scope: :badge }
end

app/models/daily_mood.rb
class DailyMood < ApplicationRecord
  belongs_to :user
  belongs_to :mood
end

app/models/habit.rb
class Habit < ApplicationRecord
    has_many :questions, dependent: :destroy
    has_many :journey_habits
    has_many :journeys, through: :journey_habits
    has_many :responses, through: :questions

    accepts_nested_attributes_for :responses

end

app/models/journey.rb
class Journey < ApplicationRecord
  belongs_to :user
  has_many :journey_lessons
  has_many :journey_habits
  has_many :lessons, through: :journey_lessons
  validates :name, presence: true
end

app/models/journey_habit.rb
class JourneyHabit < ApplicationRecord
  belongs_to :journey
  belongs_to :habit
  has_many :questions, through: :habits
  # validates_uniqueness_of :habit, conditions: -> { where("DATE(created_at) = ?", Date.today) }
  def self.totals_by_user(current_user)
    @students = User.where(teacher: false, school_class:current_user.school_class)
    @journeyhabits = JourneyHabit.where(@students.include? :user)
    @students.map do |student| 
      [
        student.first_name,
        student.journeys.last.journey_habits.count
      ]
    end
  end
end

app/models/journey_lesson.rb
class JourneyLesson < ApplicationRecord
  belongs_to :lesson
  belongs_to :journey
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  has_many :journey_lessons
  has_many :activities, dependent: :destroy
  has_many :videos, dependent: :destroy
  validates :name, :description, presence: true
end

app/models/mood.rb
class Mood < ApplicationRecord
    validates :name, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :activity, optional: true
  belongs_to :habit, optional: true
  has_many :responses
  validates :question, presence: true
end

app/models/response.rb
class Response < ApplicationRecord
  belongs_to :question
  validates :content, presence: true
  belongs_to :user
  
  
end

app/models/tool.rb
class Tool < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :journeys, dependent: :destroy
  validates :first_name, :last_name, presence: true
  has_one_attached :photo
  has_many :journey_habits, through: :journeys
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :lesson
end

app/controllers/habits_controller.rb
class HabitsController < ApplicationController
before_action :no_banner
    def show
     @habit = Habit.find(params[:id])
     @response = Response.new
     @habit_questions = @habit.questions
    @responses = @habit.responses.where(user: current_user)
    @unanswered_questions = @habit.questions - @responses.map { |r| r.question}
    @answered_questions = @responses.map { |r| r.question}
    @all_questions = @habit.questions
    @response = Response.new
    @badgesearned = []
    @journeys = current_user.journeys
    if @answered_questions.length > 0
    @habit_progress = ((@answered_questions.length.to_f / @all_questions.length.to_f)*100).to_i
    end
    # @journey_progress = ((@completed_lessons.length.to_f / @journey_lessons.length)*100).to_i
    # assigning XP and badges
    if @unanswered_questions.empty?
      @journey_habit = JourneyHabit.new(journey: current_user.journeys.last, habit: @habit)
      @journey_habit.save
      current_user.xp += @habit.xp
      current_user.save
    end
    if current_user.xp > 10
      @badge = Badge.last
      badgeuser = BadgeUser.new(user: current_user, badge: @badge)
      badgeuser.save
      @badgesearned << badgeuser
    end

    #streak logic

    @journey_habits = JourneyHabit.where(journey: @journeys.last).order('created_at DESC')
    
    unless current_user.teacher
      counter = 0
      last_habit = nil
      if @journey_habits.length > 0 && @journey_habits.first.created_at.strftime("%j").to_i == Date.today.strftime("%j").to_i
        @journey_habits.each do |journey_habit|
            if last_habit == nil
              last_habit = journey_habit
            elsif
              (last_habit.created_at.strftime("%j").to_i - journey_habit.created_at.strftime("%j").to_i) == 1
              counter += 1
              last_habit = journey_habit
            else
              break
            end
          end
          counter += 1
      end
      @streak = counter
    end


    end

end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController
  def checkin
  end

  def checkin2
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :no_banner

  def home
    @home = true
    if current_user
      @journeys = current_user.journeys
      @current_journey = @journeys.last
      redirect_to users_home_path
    # else
    #   redirect_to new_user_session_path
    end
  end

  def checkin
    @moods = Mood.all
  end

  def checkin2
    @daily_mood = DailyMood.new(user: current_user, mood:Mood.find(params["mood"].to_i))
    @daily_mood.save
    redirect_to users_home_path
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :cream_banner

  def show
    @tool = Tool.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/habits/rewards.html.erb
<div class="d-flex align-items-center" style="height:85vh">
    <div class="d-flex flex-column align-items-center">
        <div class="dashboard-element d-flex flex-column align-items-center">
            <h1>Congratulations!</h1>
            <%= image_tag 'winner.svg', alt: "congratulations!", style: "width:100%" %>
            <h3 class="mt-5">You have logged your habit and earned</h3>
            <h2><%= image_tag "095-diamond.svg", :height=>"30px" %> <strong><%= @video.xp%></strong> xp</h2>
            <canvas id="my-canvas" class="container-overlay"></canvas>
            <% if @badgesearned.length > 0 %>
                <p>You have earned the following badges</p>
                <div class="user-badges d-flex flex-wrap justify-content-center">
                    <% @badgesearned.each do |user_badge| %>
                            <div class="d-flex align-items-center flex-column user-badge">
                                <%= image_tag "badges/#{user_badge.badge.name.gsub(/\s+/, "")}.png", alt: user_badge.badge.name %>
                                <p class="mb-auto"><%= user_badge.badge.name %></p>
                            </div>
                    <% end %>
                </div>
            <% end %>
        </div>
        <%= link_to 'Continue', lesson_path(@video.lesson), class:"btn btn-main center" %>`
    </div>
</div>

app/views/habits/show.html.erb
<div class="container p-0 vh-100 flex-column">
  <% if @unanswered_questions.empty?%>
  <div class="d-flex align-items-center">
  <div class="d-flex flex-column justify-content-center align-items-center vh-100">
    <div class="d-flex flex-column align-items-center">
      <%= image_tag '009-fire.svg', alt: "congratulations!", style: "width:80%" %>
      <h3 class="mt-2">Congrats! Nice streak you've got there.</h3>
      <h2><%= image_tag "095-diamond.svg", :height=>"30px" %> <strong> + <%= @habit.xp%></strong> xp</h2>
      <canvas id="my-canvas" class="container-overlay"></canvas>
      <% if @badgesearned.length > 0 %>
        <p>You earnt new badges!</p>
        <div class="user-badges d-flex flex-wrap justify-content-center">
          <% @badgesearned.each do |user_badge| %>
            <div class="d-flex align-items-center flex-column user-badge">
              <%= image_tag "badges/#{user_badge.badge.name.gsub(/\s+/, "")}.png", alt: user_badge.badge.name %>
              <p class="mb-auto"><%= user_badge.badge.name %></p>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
      <%= link_to 'Continue', journey_habits_create_path, class:"btn btn-main center" %>
  </div>
</div>
  <% else %>
    <div class="progress ml-5 mt-4 mb-4">

        <div class="progress-bar progress-bar-striped" role="progressbar" style="width: <%= @habit_progress %>%" aria-valuenow="<%= @habit_progress %>" aria-valuemin="0" aria-valuemax="100"></div>

    </div>
    <div class="text-center">
      <h1>💤</h1>
    </div>
    <div class="pl-5 pr-5 text-center">
      <h2><strong><%= @unanswered_questions.first.question %></strong></h2>
    </div>
    <%= simple_form_for [@unanswered_questions.first, @response] do |f| %>
      <% if @unanswered_questions.first.question == "What time did you wake up?" %>
        <div class="choices">
        <% numbers = ["5 am", "5:30 am","6 am", "6:30 am","7 am", "7:30 am","8 am", "8:30 am","9 am", "9:30 am","10 am", "10 am +",] %>
        <% numbers.each do |answer| %>
              <label class="choice-number collection_radio_buttons" for="response_content_<%=answer%>"><%=answer%>
                <input class ="hiddenRadioButton" type="radio" value="<%=answer%>" name="response[content]" id="response_content_<%=answer%>">
              </label>
        <% end %>
      <% elsif @unanswered_questions.first.question == "What time did you go to bed?" %>
        <div class="choices">
        <% numbers = ["8 pm", "8:30 pm","9 pm", "9:30 pm","10 pm", "10:30 pm","11 pm", "11:30 pm","12 am", "12:30 pm","1 am", "1:30 +",] %>
        <% numbers.each do |answer| %>
              <label class="choice-number collection_radio_buttons" for="response_content_<%=answer%>"><%=answer%>
                <input class ="hiddenRadioButton" type="radio" value="<%=answer%>" name="response[content]" id="response_content_<%=answer%>">
              </label>
        <% end %>
      <% elsif @unanswered_questions.first.possible_answers.nil? %>
        <div class="choices">
        <% numbers = %w[1/10 2/10 3/10 4/10 5/10 6/10 7/10 8/10 9/10 10/10] %>
        <% numbers.each do |answer| %>
              <label class="choice-number collection_radio_buttons" for="response_content_<%=answer%>"><%=answer%>
                <input class ="hiddenRadioButton" type="radio" value="<%=answer%>" name="response[content]" id="response_content_<%=answer%>">
              </label>
        <% end %>
      </div>
      <% else %>
      <div class="choices">
        <% JSON.parse(@unanswered_questions.first.possible_answers).each do |answer| %>
          <label class="check-choice collection_check_boxes" for="response_content_<%=answer%>"><%=answer%>
            <input class="hiddenRadioButton" type="checkbox" value="<%=answer%>" name="response[content]" id="response_content_<%=answer%>">
          </label>
        <% end %>
      </div>
        
      <% end %>
        <%= f.button :submit, "Continue", class: "btn-main-activities mt-4 w-50" %>
    <% end %>
  <% end %>